---
title: "DAG_Masterarbeit"
author: "Benjamin Gottlieb"
date: "2023-10-23"
output: pdf_document
---
```{r}
library(dagitty)
library(ggdag)
library(ggplot2)
```

```{r}
dag_ma <-  dagitty('dag{
                  Water_tax [pos="0,1"]
                  Abstraction [pos="2,1"]
                  Economic_state_GDP [pos="1.25,0.5"]
                  Political_sit[pos = "0.75, 0.5"]
                  Water_resources [pos = "1, 0"]
                  Water_price [pos = "1,-0.5 "]
                  Urbanisation [pos = "0.5, 0"]
                  Height_rate[pos = "1.25,1.5"]
                  Exemptions [pos = "0.75,1.5"]
                  Other_taxes [pos = "1.5,0"]
                  
                  Water_tax <- Economic_state_GDP -> Abstraction
                  Water_tax <- Political_sit -> Abstraction
                  Water_tax <-  Water_resources -> Abstraction
                  Water_tax <-   Water_price  -> Abstraction
                  Water_tax <-   Urbanisation  -> Abstraction
                   Water_tax <-   Other_taxes-> Abstraction
                  Water_tax  -> Abstraction
                  }')

ggdag(dag_ma)+
geom_dag_text(col = "BLUE")
 
```

```{r}
coords <- list(
  x = c(y = 5, x =2, m = 4),
  y = c(y = 2, x =2, m = 2)
)

mydag_basic <- dagify(y ~ m*x ,
                      m ~ x,
                      outcome = "y",
                      coords = coords) 

ggdag_status(mydag_basic) + theme_dag() 
```

